version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: trump_trader_postgres
    environment:
      POSTGRES_DB: trump_trader
      POSTGRES_USER: trump_trader
      POSTGRES_PASSWORD: trump_trader_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trump_trader"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: trump_trader_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

